// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { Element } from "../common.sol";

struct MatchCommitmentData {
  bytes32 commitment;
  Element move;
  bool revealed;
}

library MatchCommitment {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "MatchCommitment", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746261707000000000000000000000004d61746368436f6d6d69746d656e7400);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0022030020010100000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002005f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, uint8, bool)
  Schema constant _valueSchema = Schema.wrap(0x002203005f006000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "lobbyId";
    keyNames[1] = "playerEntity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "commitment";
    fieldNames[1] = "move";
    fieldNames[2] = "revealed";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get commitment.
   */
  function getCommitment(bytes32 lobbyId, bytes32 playerEntity) internal view returns (bytes32 commitment) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get commitment.
   */
  function _getCommitment(bytes32 lobbyId, bytes32 playerEntity) internal view returns (bytes32 commitment) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set commitment.
   */
  function setCommitment(bytes32 lobbyId, bytes32 playerEntity, bytes32 commitment) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((commitment)), _fieldLayout);
  }

  /**
   * @notice Set commitment.
   */
  function _setCommitment(bytes32 lobbyId, bytes32 playerEntity, bytes32 commitment) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((commitment)), _fieldLayout);
  }

  /**
   * @notice Get move.
   */
  function getMove(bytes32 lobbyId, bytes32 playerEntity) internal view returns (Element move) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Element(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get move.
   */
  function _getMove(bytes32 lobbyId, bytes32 playerEntity) internal view returns (Element move) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Element(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set move.
   */
  function setMove(bytes32 lobbyId, bytes32 playerEntity, Element move) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(move)), _fieldLayout);
  }

  /**
   * @notice Set move.
   */
  function _setMove(bytes32 lobbyId, bytes32 playerEntity, Element move) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(move)), _fieldLayout);
  }

  /**
   * @notice Get revealed.
   */
  function getRevealed(bytes32 lobbyId, bytes32 playerEntity) internal view returns (bool revealed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get revealed.
   */
  function _getRevealed(bytes32 lobbyId, bytes32 playerEntity) internal view returns (bool revealed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set revealed.
   */
  function setRevealed(bytes32 lobbyId, bytes32 playerEntity, bool revealed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((revealed)), _fieldLayout);
  }

  /**
   * @notice Set revealed.
   */
  function _setRevealed(bytes32 lobbyId, bytes32 playerEntity, bool revealed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((revealed)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 lobbyId, bytes32 playerEntity) internal view returns (MatchCommitmentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 lobbyId, bytes32 playerEntity) internal view returns (MatchCommitmentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 lobbyId, bytes32 playerEntity, bytes32 commitment, Element move, bool revealed) internal {
    bytes memory _staticData = encodeStatic(commitment, move, revealed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 lobbyId, bytes32 playerEntity, bytes32 commitment, Element move, bool revealed) internal {
    bytes memory _staticData = encodeStatic(commitment, move, revealed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 lobbyId, bytes32 playerEntity, MatchCommitmentData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.commitment, _table.move, _table.revealed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 lobbyId, bytes32 playerEntity, MatchCommitmentData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.commitment, _table.move, _table.revealed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (bytes32 commitment, Element move, bool revealed) {
    commitment = (Bytes.getBytes32(_blob, 0));

    move = Element(uint8(Bytes.getBytes1(_blob, 32)));

    revealed = (_toBool(uint8(Bytes.getBytes1(_blob, 33))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (MatchCommitmentData memory _table) {
    (_table.commitment, _table.move, _table.revealed) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 lobbyId, bytes32 playerEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 lobbyId, bytes32 playerEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 commitment, Element move, bool revealed) internal pure returns (bytes memory) {
    return abi.encodePacked(commitment, move, revealed);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 commitment,
    Element move,
    bool revealed
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(commitment, move, revealed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 lobbyId, bytes32 playerEntity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = lobbyId;
    _keyTuple[1] = playerEntity;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
