// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum LobbyStatus {
  None,
  Open,
  Matched,
  Resolved,
  Cancelled
}

enum Element {
  None,
  Fire,
  Water,
  Earth
}
