// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CrystalData, CrystalDataData } from "./tables/CrystalData.sol";
import { ManaBalance } from "./tables/ManaBalance.sol";
import { ArenaLobby, ArenaLobbyData } from "./tables/ArenaLobby.sol";
import { MatchCommitment, MatchCommitmentData } from "./tables/MatchCommitment.sol";
import { CrystalOwner } from "./tables/CrystalOwner.sol";
import { ForgeConfig, ForgeConfigData } from "./tables/ForgeConfig.sol";
import { StarterManaClaimed } from "./tables/StarterManaClaimed.sol";
import { ForgeNonce } from "./tables/ForgeNonce.sol";
