// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Element } from "../common.sol";

/**
 * @title IArenaSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IArenaSystem {
  error ArenaSystem_UnknownCrystal(bytes32 entity);
  error ArenaSystem_ZeroWager();
  error ArenaSystem_EmptyCommitment();
  error ArenaSystem_InsufficientMana(bytes32 entity, uint128 balance, uint128 required);
  error ArenaSystem_LobbyAlreadyExists(bytes32 lobbyId);
  error ArenaSystem_LobbyNotOpen(bytes32 lobbyId);
  error ArenaSystem_LobbyNotMatched(bytes32 lobbyId);
  error ArenaSystem_SelfMatch(bytes32 entity);
  error ArenaSystem_NotChallenger(bytes32 lobbyId, bytes32 entity);
  error ArenaSystem_NotAParticipant(bytes32 lobbyId, bytes32 entity);
  error ArenaSystem_InvalidMove();
  error ArenaSystem_AlreadyRevealed(bytes32 lobbyId, bytes32 entity);
  error ArenaSystem_CommitmentMismatch(bytes32 lobbyId, bytes32 entity);
  error ArenaSystem_RevealWindowClosed(bytes32 lobbyId);
  error ArenaSystem_RevealWindowOpen(bytes32 lobbyId);
  error ArenaSystem_RevealPending(bytes32 lobbyId);
  error ArenaSystem_BothRevealed(bytes32 lobbyId);
  error ArenaSystem_PotOverflow(bytes32 entity);

  function app__createLobby(bytes32 lobbySalt, uint128 wager, bytes32 commitment) external returns (bytes32 lobbyId);

  function app__joinLobby(bytes32 lobbyId, bytes32 commitment) external;

  function app__revealMove(bytes32 lobbyId, Element move, bytes32 salt) external;

  function app__resolveMatch(bytes32 lobbyId) external returns (bytes32 winner);

  function app__claimTimeout(bytes32 lobbyId) external returns (bytes32 winner);

  function app__cancelLobby(bytes32 lobbyId) external;
}
