// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICrystalForgeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICrystalForgeSystem {
  error CrystalForge_ZeroRecipient();
  error CrystalForge_NotConfigured();
  error CrystalForge_InvalidConfig();
  error CrystalForge_AlreadyMinted(uint256 minted);
  error CrystalForge_EntityCollision(bytes32 entity, uint256 tokenId);
  error CrystalForge_MintPriceNotConfigured();
  error CrystalForge_IncorrectPayment(uint256 expected, uint256 provided);
  error CrystalForge_NotTheCrystalFacade(address caller);

  function app__configureForge(
    address accountRegistry,
    address accountImplementation,
    address tokenContract,
    bytes32 accountSalt
  ) external;

  function app__setMintPrice(uint256 price) external;

  function app__mintCrystal(address to) external payable returns (bytes32 entity, uint256 tokenId);

  function app__crystalAccountOf(uint256 tokenId) external view returns (address);

  function app__crystalEntityOf(uint256 tokenId) external view returns (bytes32);

  function app__mintRevenue() external view returns (uint256);

  function app__mintPrice() external view returns (bool configured, uint256 price);
}
