// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IProgressionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IProgressionSystem {
  error Progression_UnknownCrystal(bytes32 entity);
  error Progression_StarterManaAlreadyClaimed(bytes32 entity);
  error Progression_InsufficientMana(bytes32 entity, uint128 balance, uint128 required);
  error Progression_MaxLevelReached(bytes32 entity, uint8 level);
  error Progression_ManaOverflow(bytes32 entity);

  function app__claimStarterMana() external returns (uint128 amount);

  function app__levelUp() external returns (uint8 newLevel);

  function app__levelUpCost(bytes32 entity) external view returns (uint128);

  function app__canClaimStarterMana(bytes32 entity) external view returns (bool);
}
