// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITokenBridgeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenBridgeSystem {
  error TokenBridge_InvalidFacade();
  error TokenBridge_NotTheCrystalFacade(address caller);
  error TokenBridge_NotTheManaFacade(address caller);
  error TokenBridge_UnknownCrystal(uint256 tokenId);
  error TokenBridge_WrongOwner(uint256 tokenId, address claimed, address actual);
  error TokenBridge_ZeroRecipient();
  error TokenBridge_AmountTooLarge(uint256 amount);
  error TokenBridge_InsufficientMana(address from, uint256 balance, uint256 amount);
  error TokenBridge_ManaOverflow(address to);

  function app__setTokenFacades(address crystalNft, address manaToken) external;

  function app__transferCrystal(address from, address to, uint256 tokenId) external;

  function app__transferMana(address from, address to, uint256 amount) external;

  function app__ownerOfCrystal(uint256 tokenId) external view returns (address);

  function app__crystalBalanceOf(address owner) external view returns (uint256);

  function app__manaBalanceOf(address account) external view returns (uint256);

  function app__manaTotalSupply() external view returns (uint256);

  function app__tokenFacades() external view returns (address crystalNft, address manaToken);
}
